"""
Generate professional investment reports from agent analysis.
"""
from datetime import datetime
from jinja2 import Template
import os


class ReportGenerator:
    """Generate markdown investment reports"""
    
    REPORT_TEMPLATE = """# Investment Analysis Report: {{ symbol }}
**Generated:** {{ date }}
**Analysis Type:** {{ analysis_type }}

---

## Executive Summary
{{ summary }}

---

{{ full_analysis }}

---

## Disclaimer
This analysis is provided for informational purposes only and should not be considered financial advice.
Always consult with a qualified financial advisor before making investment decisions.

---

*Generated by FinanceBot - AI-Powered Investment Analysis*
"""
    
    def generate_markdown(self, symbol: str, analysis: str, analysis_type: str = "comprehensive") -> str:
        """Generate markdown report."""
        template = Template(self.REPORT_TEMPLATE)
        sentences = analysis.split('.')[:3]
        summary = '. '.join(sentences) + '.'
        
        report = template.render(
            symbol=symbol,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            analysis_type=analysis_type,
            summary=summary,
            full_analysis=analysis
        )
        
        return report
    
    @staticmethod
    def save_report(report: str, symbol: str, folder: str = "reports") -> str:
        """Save report to file."""
        os.makedirs(folder, exist_ok=True)
        filename = f"{folder}/{symbol}_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return filename
    
    @staticmethod
    def markdown_to_html(markdown: str) -> str:
        """Convert markdown to HTML for web display"""
        import markdown
        html = markdown.markdown(markdown)
        return html